services:
  budget-mcp-server:
    build: .
    profiles:
      - prod
    environment:
      - APP_ENV=production
      - DATABASE_FILE=/app/data/budget_app.duckdb
      - HOST=0.0.0.0
      - PORT=8000
      - MCP_PATH=/mcp
    ports:
      - "8000:8000"
    volumes:
      - budget_data:/app/data
    restart: unless-stopped

  budget-mcp-server-dev:
    build: .
    environment:
      - APP_ENV=development
      - DATABASE_FILE=/app/data/budget_app.duckdb
      - HOST=0.0.0.0
      - PORT=8000
      - MCP_PATH=/mcp
    ports:
      - "8000:8000"
    volumes:
      - budget_data:/app/data
      - .:/app
    profiles:
      - dev
    restart: unless-stopped

volumes:
  budget_data:
