services:
  budget-mcp-server:
    build: .
    image: budget-mcp-server:latest
    container_name: budget-mcp-server
    profiles:
      - prod
    command: >
      bash -c "uvx -n --from . budget-mcp-server"
    environment:
      - APP_ENV=production
      - DATABASE_FILE=/app/data/budget_app.duckdb
      - DATABASE_MODE=hybrid
      - MOTHERDUCK_TOKEN=${MOTHERDUCK_TOKEN}
      - MOTHERDUCK_DATABASE=budget_app
      - MOTHERDUCK_SYNC_ON_START=false
    volumes:
      - budget_data:/app/data
    restart: unless-stopped
    networks:
      - default

    # Configure stdin/stdout for MCP server communication
    stdin_open: true
    tty: true

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  budget-mcp-server-http:
    build: .
    image: budget-mcp-server:latest
    container_name: budget-mcp-server
    profiles:
      - prod-http
    command: >
      bash -c "uv run python3 run.py"
    environment:
      - APP_ENV=production
      - DATABASE_FILE=/app/data/budget_app.duckdb
      - DATABASE_MODE=hybrid
      - MOTHERDUCK_TOKEN=${MOTHERDUCK_TOKEN}
      - MOTHERDUCK_DATABASE=budget_app
      - HOST=0.0.0.0
      - PORT=8443
      - MCP_PATH=/mcp
      - HTTPS_ENABLED=true
      - BEARER_TOKEN=${BEARER_TOKEN}
    ports:
      - "8443:8443"  # HTTPS port
    volumes:
      - budget_data:/app/data
      - ./certs:/app/certs:ro
    restart: unless-stopped
    networks:
      - default

  budget-mcp-server-dev-http:
    build: .
    image: budget-mcp-server:dev
    container_name: budget-mcp-server-dev
    profiles:
      - dev-http
    command: >
      bash -c "if [ -f /usr/local/share/ca-certificates/server.crt ]; then update-ca-certificates; fi && uv run python3 run.py"
    environment:
      - APP_ENV=development
      - DATABASE_FILE=/app/data/budget_app.duckdb
      - DATABASE_MODE=hybrid
      - MOTHERDUCK_TOKEN=${MOTHERDUCK_TOKEN}
      - MOTHERDUCK_DATABASE=budget_app
      - HOST=0.0.0.0
      - PORT=8000
      - MCP_PATH=/mcp
      - HTTPS_ENABLED=false
      - SSL_KEY_FILE=/app/certs/server.key
      - BEARER_TOKEN=${BEARER_TOKEN}
    ports:
      - "8000:8000"  # HTTP port
    volumes:
      - budget_data:/app/data
      - ./certs:/app/certs:ro
      - ./certs/server.crt:/usr/local/share/ca-certificates/server.crt:ro
      - .:/app
    restart: unless-stopped
    networks:
      - default

  budget-mcp-server-dev:
    build: .
    image: budget-mcp-server:dev
    container_name: budget-mcp-server-dev-stdio
    profiles:
      - dev
    command: >
      bash -c "uvx -n --from . budget-mcp-server"
    environment:
      - APP_ENV=development
      - DATABASE_FILE=./data/budget_app.duckdb
      - DATABASE_MODE=hybrid
      - MOTHERDUCK_TOKEN=${MOTHERDUCK_TOKEN}
      - MOTHERDUCK_DATABASE=budget_app
      - MOTHERDUCK_SYNC_ON_START=false
    volumes:
      - budget_data:/app/data
      - .:/app
    restart: unless-stopped
    networks:
      - default

    # Configure stdin/stdout for MCP server communication
    stdin_open: true
    tty: true

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  budget_data:

networks:
  default:
    name: budget-mcp-server_default
