services:
  budget-mcp-server:
    build: .
    image: budget-mcp-server:latest
    container_name: budget-mcp-server
    profiles:
      - prod
    environment:
      - APP_ENV=production
      - DATABASE_FILE=/app/data/budget_app.duckdb
      - HOST=0.0.0.0
      - PORT=8443
      - MCP_PATH=/mcp
      - HTTPS_ENABLED=true
      - SSL_CERT_FILE=/app/certs/server.crt
      - SSL_KEY_FILE=/app/certs/server.key
    ports:
      - "8000:8000"
      - "8443:8443"  # HTTPS port
    volumes:
      - budget_data:/app/data
      - budget_certs:/app/certs  # SSL certificates volume
      - ./certs:/app/certs  # Mount host certificates directory
    restart: unless-stopped
    networks:
      - default

  budget-mcp-server-dev:
    build: .
    image: budget-mcp-server:dev
    container_name: budget-mcp-server-dev
    environment:
      - APP_ENV=development
      - DATABASE_FILE=/app/data/budget_app.duckdb
      - HOST=0.0.0.0
      - PORT=8443
      - MCP_PATH=/mcp
      - HTTPS_ENABLED=true
      - SSL_CERT_FILE=/app/certs/server.crt
      - SSL_KEY_FILE=/app/certs/server.key
    ports:
      - "8000:8000"
      - "8443:8443"  # HTTPS port
    volumes:
      - budget_data:/app/data
      - budget_certs:/app/certs  # SSL certificates volume
      - ./certs:/app/certs  # Mount host certificates directory
      - .:/app
    restart: unless-stopped
    networks:
      - default

volumes:
  budget_data:
  budget_certs:

networks:
  default:
    name: budget-mcp-server_default
