version: '3.8'

services:
  budget-mcp-server:
    build: .
    profiles:
      - prod
    environment:
      - FLASK_ENV=production
      - DATABASE_FILE=/app/data/budget_app.duckdb
    volumes:
      - budget_data:/app/data
    restart: unless-stopped

  budget-mcp-server-dev:
    build: .
    environment:
      - FLASK_ENV=development
      - DATABASE_FILE=/app/data/budget_app.duckdb
    volumes:
      - budget_data:/app/data
      - .:/app
    profiles:
      - dev
    restart: unless-stopped

volumes:
  budget_data:
