services:
  budget-mcp-server:
    build: .
    image: budget-mcp-server:latest
    container_name: budget-mcp-server
    profiles:
      - prod
    environment:
      - APP_ENV=production
      - DATABASE_FILE=/app/data/budget_app.duckdb
      - HOST=0.0.0.0
      - PORT=8000
      - MCP_PATH=/mcp
    ports:
      - "8000:8000"
    volumes:
      - budget_data:/app/data
    restart: unless-stopped
    networks:
      - default

  budget-mcp-server-dev:
    build: .
    image: budget-mcp-server:dev
    container_name: budget-mcp-server-dev
    environment:
      - APP_ENV=development
      - DATABASE_FILE=/app/data/budget_app.duckdb
      - HOST=0.0.0.0
      - PORT=8000
      - MCP_PATH=/mcp
    ports:
      - "8000:8000"
    volumes:
      - budget_data:/app/data
      - .:/app
    restart: unless-stopped
    networks:
      - default

volumes:
  budget_data:

networks:
  default:
    name: budget-mcp-server_default
