[project]
name = "budget-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=0.8.0", # Matched with requirements.txt
    "fastmcp>=2.3.0",
    "mcp>=1.9.4",
]

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0", # Matched with requirements.txt (original was >=8.4.1, req has >=7.0.0)
    "pytest-asyncio>=0.18.0"
]

[tool.setuptools.packages.find]
include = ["app*"]
